### ISSUE TITLE
Load model ValueError: Wrong Size

### ISSUE THREAD

**Issue by binjiaqm** [huggingface/neuralcoref#118]
nlp = spacy.load('en_coref_md')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\spacy\__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\spacy\util.py", line 114, in load_model
    return load_model_from_package(name, **overrides)
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\spacy\util.py", line 134, in load_model_from_package
    cls = importlib.import_module(name)
  File "C:\ProgramData\Anaconda3\envs\py36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\en_coref_md\__init__.py", line 6, in <module>
    from en_coref_md.neuralcoref import NeuralCoref
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\en_coref_md\neuralcoref\__init__.py", line 1, in <module>
    from .neuralcoref import NeuralCoref
  File "cymem.pxd", line 1, in init en_coref_md.neuralcoref.neuralcoref
ValueError: cymem.cymem.Pool has the wrong size, try recompiling. Expected 64, got 48

**Comment by binjiaqm** [comment]
pip install spacy==2.0.12
