### ISSUE TITLE
CORPUS.build_and_gather_multiple_arrays(SAVE_DIR)

### ISSUE THREAD

**Issue by Hareem9292** [huggingface/neuralcoref#121]
let me explain about my virtual environment and python version.
virtual environment: (.enviroment27adm)
Python version: python2.7 with anaconda

I have already tried all these commands in python 3.7 as well and got the same error that is mentioned below. So, I think there is no python version issue. 

i have tried  this command **python -m neuralcoref.conllparser --path ./data/train/** and i got this error.

(.enviroment27adm) (py27) C:\Windows\System32>python -m neuralcoref.conllparser --path ./data/train/
C:\WINDOWS\system32\.enviroment27adm\Scripts\python.exe: No module named neuralcoref.conllparser

then I modified this command little bit and tried this one **python -m conllparser --path ./data/train/** after setting the files directories.

(.enviroment27adm) (py27) C:\Windows\System32\neuralcoref\neuralcoref\train>python -m conllparser --path ./data/train/
Loading embeddings from C:\Windows\System32\neuralcoref\neuralcoref\train/weights/static_word
Loading embeddings from C:\Windows\System32\neuralcoref\neuralcoref\train/weights/tuned_word
 Reading files
In ./data/train/ C:\Windows\System32\neuralcoref\neuralcoref\train\data\train
In ./data/train/numpy C:\Windows\System32\neuralcoref\neuralcoref\train\data\train\numpy
utts_text size 0
utts_tokens size 0
utts_corefs size 0
utts_speakers size 0
utts_doc_idx size 0
 Building docs
 Loading spacy model

    [93mInfo about model en_core_web_sm[0m

    lang               en
    pipeline           [u'tagger', u'parser', u'ner']
    name               core_web_sm
    license            CC BY-SA 3.0
    author             Explosion AI
    url                https://explosion.ai
    description        English multi-task CNN trained on OntoNotes, with GloVe vectors trained on Common Crawl. Assigns word vectors, context-specific token vectors, POS tags, dependency parse and named entities.
    vectors            {u'keys': 0, u'width': 0, u'vectors': 0}
    sources            [u'OntoNotes 5', u'Common Crawl']
    version            2.0.0
    source             C:\WINDOWS\system32\.enviroment27adm\lib\site-packages\en_core_web_sm
    spacy_version      >=2.0.0a18
    parent_package     spacy
    speed              {u'gpu': None, u'nwords': 291344, u'cpu': 5122.3040471407}
    email              contact@explosion.ai
    accuracy           {u'token_acc': 99.8698372794, u'ents_p': 84.9664503965, u'ents_r': 85.6312524451, u'uas': 91.7237657538, u'tags_acc': 97.0403350292, u'ents_f': 85.2975560875, u'las': 89.800872413}

 Parsing utterances and filling docs
0it [00:00, ?it/s]
=> read_corpus time elapsed 3.31200003624
 Extracting mentions features
0it [00:00, ?it/s]
 Building and gathering arrays
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "c:\users\haree\anaconda3\envs\py27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\haree\anaconda3\envs\py27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Windows\System32\neuralcoref\neuralcoref\train\conllparser.py", line 714, in <module>
    CORPUS.build_and_gather_multiple_arrays(SAVE_DIR)
  File "C:\Windows\System32\neuralcoref\neuralcoref\train\conllparser.py", line 649, in build_and_gather_multiple_arrays
    print("Building numpy array for", feature, "length", len(gathering_dict[feature]))
TypeError: object of type 'NoneType' has no len()

Now I am getting these errors. Please help me how can i resolve them?

**Comment by felialois** [comment]
I'm getting the same error. Did you ever manage to find a solution? Thanks

**Comment by thomwolf** [comment]
The training scripts are out-dated for the moment. Up-dating them is next on my to-do list for this repo but I don't have an ETA for the moment.

**Comment by svlandeg** [comment]
In case anyone stumbles upon this issue through Google: check the logs produced by the script, it shows `utts_text size 0`, `0it [00:00, ?it/s]`, etc. There have been no articles parsed, resulting in an error downstream. The path to the training directory `--path ./data/train/` is probably wrong in your original command, you need to adjust it to point to the folder which holds the file `train.english.v4_gold_conll` (or similar) on your system.
