### ISSUE TITLE
Install Errors with neuralcoref

### ISSUE THREAD

**Issue by riyer15** [huggingface/neuralcoref#142]
`MacBooks-MacBook-Pro:neuralcoref macbookpro$ pip install -e .
Obtaining file:///Users/macbookpro/Documents/Penn-Year-4/senior-design/neuralcoref
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'Cython'
    Processing neuralcoref.pyx
    Traceback (most recent call last):
      File "/Users/macbookpro/Documents/Penn-Year-4/senior-design/neuralcoref/bin/cythonize.py", line 59, in process_pyx
        env=os.environ) # See Issue #791
      File "/Users/macbookpro/miniconda3/lib/python3.6/subprocess.py", line 267, in call
        with Popen(*popenargs, **kwargs) as p:
      File "/Users/macbookpro/miniconda3/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/Users/macbookpro/miniconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cython': 'cython'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/macbookpro/Documents/Penn-Year-4/senior-design/neuralcoref/bin/cythonize.py", line 157, in <module>
        run(args.root)
      File "/Users/macbookpro/Documents/Penn-Year-4/senior-design/neuralcoref/bin/cythonize.py", line 148, in run
        process(base, filename, db)
      File "/Users/macbookpro/Documents/Penn-Year-4/senior-design/neuralcoref/bin/cythonize.py", line 114, in process
        preserve_cwd(base, process_pyx, root + '.pyx', root + '.cpp')
      File "/Users/macbookpro/Documents/Penn-Year-4/senior-design/neuralcoref/bin/cythonize.py", line 79, in preserve_cwd
        func(*args)
      File "/Users/macbookpro/Documents/Penn-Year-4/senior-design/neuralcoref/bin/cythonize.py", line 70, in process_pyx
        raise Exception('Cython failed')
    Exception: Cython failed
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/macbookpro/Documents/Penn-Year-4/senior-design/neuralcoref/setup.py", line 108, in <module>
        setup_package()
      File "/Users/macbookpro/Documents/Penn-Year-4/senior-design/neuralcoref/setup.py", line 51, in setup_package
        generate_cython(root, 'neuralcoref')
      File "/Users/macbookpro/Documents/Penn-Year-4/senior-design/neuralcoref/setup.py", line 40, in generate_cython
        raise RuntimeError('Running cythonize failed')
    RuntimeError: Running cythonize failed
    Cythonizing sources

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/macbookpro/Documents/Penn-Year-4/senior-design/neuralcoref/`

I've tried all the fixes described here and online, and I can't seem to figure out the issue. I'm running the command in a virtualenv, which could be the source of the error " No such file or directory: 'cython': 'cython'" (because i can see cython in my directories). Does anyone have any advice?

**Comment by riyer15** [comment]
Fixed - Had to sudo pip install Cython in the neuralcoref directory.
