### ISSUE TITLE
Cannot load model: python 3.6/3.7, spacy 2.1.3

### ISSUE THREAD

**Issue by sidnarayanan** [huggingface/neuralcoref#147]
Hi!

I'm having a bit of trouble installing any of the neuralcoref models. I've tried the following steps on Ubuntu 18.04 (python 3.6.7) and OSX Mojave (3.7.3). 

1. Install spacy 2.1.3, check that I can properly load and run models. 
2. Install a neuralcoref model via pip:
```
$ pip3 install https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_lg-3.0.0/en_coref_lg-3.0.0.tar.gz
```
3. Try to load the model, either by importing it directly or loading via spacy:
```python
>>> import en_coref_lg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/en_coref_lg/__init__.py", line 6, in <module>
    from en_coref_lg.neuralcoref import NeuralCoref
  File "/usr/local/lib/python3.6/dist-packages/en_coref_lg/neuralcoref/__init__.py", line 1, in <module>
    from .neuralcoref import NeuralCoref
  File "cymem.pxd", line 1, in init en_coref_lg.neuralcoref.neuralcoref
ValueError: cymem.cymem.Pool has the wrong size, try recompiling. Expected 64, got 48
>>> import spacy; nlp = spacy.load('en_coref_lg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 131, in load_model
    return load_model_from_package(name, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 152, in load_model_from_package
    return cls.load(**overrides)
  File "/usr/local/lib/python3.6/dist-packages/en_coref_lg/__init__.py", line 14, in load
    nlp = load_model_from_init_py(__file__, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 190, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 173, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/usr/local/lib/python3.6/dist-packages/spacy/language.py", line 786, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 611, in from_disk
    reader(path / key)
  File "/usr/local/lib/python3.6/dist-packages/spacy/language.py", line 776, in <lambda>
    deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(p, exclude=["vocab"])
  File "tokenizer.pyx", line 390, in spacy.tokenizer.Tokenizer.from_disk
  File "tokenizer.pyx", line 436, in spacy.tokenizer.Tokenizer.from_bytes
  File "/usr/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.6/sre_parse.py", line 527, in _parse
    code1 = _class_escape(source, this)
  File "/usr/lib/python3.6/sre_parse.py", line 336, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
sre_constants.error: bad escape \p at position 275
```

I've checked both the medium and large models and get the same error. Any help would be appreciated!

**Comment by dpasch01** [comment]
Same error here. I am using the medium model with spaCy 2.1.3 and python 3.6.7

**Comment by sidnarayanan** [comment]
As a temporary fix, I was able to install the development branch from source, and it appears to work fine. Still, it would be helpful to understand why the official release doesn't work, since I think I'm using a pretty vanilla environment.

**Comment by Vimos** [comment]
Today, the master branch seems the same with dev branch, I also get the same error.
```
/home/vimos/anaconda3/envs/rcqa/bin/python3.7 /snap/pycharm-professional/127/helpers/pydev/pydevconsole.py --mode=client --port=38489
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['/home/vimos/git/QA/rcqa', '/home/vimos/git/QA/rcqa/vjoy/backend', '/home/vimos/git/QA/rcqa/examples/hotpot', '/home/vimos/git/QA/rcqa/examples/qangaroo'])
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.4.0
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] on linux
runfile('/home/vimos/git/QA/rcqa/examples/qangaroo/wikihop_rgcn.py', wdir='/home/vimos/git/QA/rcqa/examples/qangaroo')
Traceback (most recent call last):
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-d09afabb8c7d>", line 1, in <module>
    runfile('/home/vimos/git/QA/rcqa/examples/qangaroo/wikihop_rgcn.py', wdir='/home/vimos/git/QA/rcqa/examples/qangaroo')
  File "/snap/pycharm-professional/127/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/snap/pycharm-professional/127/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/vimos/git/QA/rcqa/examples/qangaroo/wikihop_rgcn.py", line 19, in <module>
    from qa_qangaroo.graph import WikiHop, batcher, evaluate
  File "/snap/pycharm-professional/127/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/vimos/git/QA/rcqa/examples/qangaroo/qa_qangaroo/graph.py", line 30, in <module>
    nlp = spacy.load('en_core_web_sm')
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/site-packages/spacy/util.py", line 131, in load_model
    return load_model_from_package(name, **overrides)
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/site-packages/spacy/util.py", line 152, in load_model_from_package
    return cls.load(**overrides)
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/site-packages/en_core_web_sm/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/site-packages/spacy/util.py", line 190, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/site-packages/spacy/util.py", line 173, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/site-packages/spacy/language.py", line 786, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/site-packages/spacy/util.py", line 611, in from_disk
    reader(path / key)
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/site-packages/spacy/language.py", line 776, in <lambda>
    deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(p, exclude=["vocab"])
  File "tokenizer.pyx", line 390, in spacy.tokenizer.Tokenizer.from_disk
  File "tokenizer.pyx", line 436, in spacy.tokenizer.Tokenizer.from_bytes
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/sre_parse.py", line 536, in _parse
    code1 = _class_escape(source, this)
  File "/home/vimos/anaconda3/envs/rcqa/lib/python3.7/sre_parse.py", line 337, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
re.error: bad escape \p at position 257
```

However, after download a new SpaCy model, the error is gone.
```
(rcqa) ➜  ~ python -m spacy download en_core_web_sm                                                                                                                                        [19/04/9| 2:12PM]

Collecting en_core_web_sm==2.1.0 from https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz#egg=en_core_web_sm==2.1.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz (11.1MB)
    100% |████████████████████████████████| 11.1MB 524kB/s 
Installing collected packages: en-core-web-sm
  Found existing installation: en-core-web-sm 2.0.0
    Uninstalling en-core-web-sm-2.0.0:
      Successfully uninstalled en-core-web-sm-2.0.0
  Running setup.py install for en-core-web-sm ... done
Successfully installed en-core-web-sm-2.1.0
✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_sm')
```

**Comment by sidnarayanan** [comment]
Indeed, looks like 4.0 is the official release now. Guess this issue can be closed.
