### ISSUE TITLE
MemoryError in conllparser.py

### ISSUE THREAD

**Issue by svlandeg** [huggingface/neuralcoref#212]
Running into memory issues with the `conllparser.py`
For the (english) development data, `conllparser.py --path ../../data/dev` works fine, but it crashes on the training data with `conllparser.py --path ../../data/train`:

```
Loaded model en_core_web_md
Parsing utterances and filling docs
75187it [04:15, 294.22it/s]
=> read_corpus time elapsed 275.47436809539795
Extracting mentions features
100%|██████████| 2792/2792 [03:25<00:00, 13.60it/s]
Building and gathering arrays
 53%|█████▎    | 1466/2792 [08:06<31:07,  1.41s/it]Traceback (most recent call last):
  File "C:/Users/Sofie/Documents/git/neuralcoref/neuralcoref/train/conllparser.py", line 732, in <module>
    CORPUS.build_and_gather_multiple_arrays(SAVE_DIR)
  File "C:/Users/Sofie/Documents/git/neuralcoref/neuralcoref/train/conllparser.py", line 637, in build_and_gather_multiple_arrays
    arrays_dicts = parallel_process(arr, get_feats, use_kwargs=True, n_jobs=self.n_jobs)
  File "C:\Users\Sofie\Documents\git\neuralcoref\neuralcoref\train\utils.py", line 78, in parallel_process
    return front + [function(**a) if use_kwargs else function(a) for a in tqdm(array[front_num:])]
  File "C:\Users\Sofie\Documents\git\neuralcoref\neuralcoref\train\utils.py", line 78, in <listcomp>
    return front + [function(**a) if use_kwargs else function(a) for a in tqdm(array[front_num:])]
  File "C:/Users/Sofie/Documents/git/neuralcoref/neuralcoref/train/conllparser.py", line 239, in get_feats
    return doc.get_feature_array(doc_id=i)
  File "C:/Users/Sofie/Documents/git/neuralcoref/neuralcoref/train/conllparser.py", line 421, in get_feature_array
    pairs_labels += ant_labels
MemoryError
 53%|█████▎    | 1466/2792 [08:09<07:22,  3.00it/s]
```

**Comment by svlandeg** [comment]
If I set `use_gold_mentions=True`, this `MemoryError` doesn't happen.

**Comment by svlandeg** [comment]
Fixed by using high-mem EC2 instance, but adding "check memory usage" to the TODO list.
