### ISSUE TITLE
ValueError: Unpack failed: incomplete input

### ISSUE THREAD

**Issue by M-M-dot** [huggingface/neuralcoref#244]
Hi,
I met this problem when I use neuralcoref.  
I create a new environment `python -m venv .env2` and installed neuralcoref from source.  

The following below is my code
```
import spacy
import neuralcoref

f = open("SongOfIceAndFire/1.AGameOfThrones-George.txt","r",encoding="utf-8")
texts = f.read()
f.close()

texts = texts.replace('\n'," ")
docs = texts.split(".")


nlp = spacy.load('en_core_web_sm') 

neuralcoref.add_to_pipe(nlp)
nlp_docs = nlp.pipe(docs)
result_docs = []
for nlp_doc in nlp_docs:
    new_list = []
    for ent in nlp_doc.ents:
        new_list.append((ent.text, ent.label_,ent.start,ent))
    result_docs.append(new_list)
print(result_docs)
```
This is error message
```
Traceback (most recent call last):
  File "B:/当前任务/Science_Fiction/Spacy_entity/test_spacy.py", line 14, in <module>
    neuralcoref.add_to_pipe(nlp)
  File "b:\当前任务\science_fiction\spacy_entity\.env2\neuralcoref\neuralcoref\__init__.py", line 42, in add_to_pipe
    coref = NeuralCoref(nlp.vocab, **kwargs)
  File "neuralcoref.pyx", line 554, in neuralcoref.neuralcoref.NeuralCoref.__init__
  File "neuralcoref.pyx", line 947, in neuralcoref.neuralcoref.NeuralCoref.from_disk
  File "B:\当前任务\Science_Fiction\Spacy_entity\.env2\lib\site-packages\thinc\neural\_classes\model.py", line 355, in from_bytes
    data = srsly.msgpack_loads(bytes_data)
  File "B:\当前任务\Science_Fiction\Spacy_entity\.env2\lib\site-packages\srsly\_msgpack_api.py", line 29, in msgpack_loads
    msg = msgpack.loads(data, raw=False, use_list=use_list)
  File "B:\当前任务\Science_Fiction\Spacy_entity\.env2\lib\site-packages\srsly\msgpack\__init__.py", line 60, in unpackb
    return _unpackb(packed, **kwargs)
  File "_unpacker.pyx", line 203, in srsly.msgpack._unpacker.unpackb
ValueError: Unpack failed: incomplete input
```

**Comment by svlandeg** [comment]
Did you install spaCy from source? And what is the version of srsly in your environment?

Also, I've no idea whether that could be related, but it looks like there are unicode characters in your pathname, maybe that's causing trouble? Could you try running all this from a fresh virtual environment that doesn't have such characters?

**Comment by M-M-dot** [comment]
Thanks, I just solved this problem. I guess , at first, when `import neuralcoref`,  it didn't download the model completely . so, I deleted  the director `.neuralcoref_cache`  and ran the codes again.  It works.

**Comment by svlandeg** [comment]
Thanks for sharing, happy to hear you found a solution!
