### ISSUE TITLE
`NotADirectoryError` while trainling neuralcoref on a new dataset

### ISSUE THREAD

**Issue by negacy** [huggingface/neuralcoref#33]
I am following the documentation to train the neuralcoref system on my own dataset. I have my dataset in CoNLL format and when I run the script `python -m neuralcoref.conllparser --path path-to-my-dataset`, I have the following error. Any suggestion please?

Traceback (most recent call last):
  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/neha5486/git/neuralcoref/neuralcoref/conllparser.py", line 702, in <module>
    os.makedirs(SAVE_DIR)
  File "/opt/python/3.6.3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
NotADirectoryError: [Errno 20] Not a directory: '/scratch/Shares/hunter/ontonotes/train.english.v4_gold_conll/numpy/'

**Comment by thomwolf** [comment]
Hi @negacy, the path to your dataset is probably wrong.
It should just be the path to the folder containing your data, not to the file itself (the parser will create a directory inside this data folder to host the numpy arrays created after parsing the files)

**Comment by negacy** [comment]
Right, the problem was with the path. Thanks. Negacy.

**Comment by HeebahsaleemGist** [comment]
> Hi @negacy, the path to your dataset is probably wrong.
> It should just be the path to the folder containing your data, not to the file itself (the parser will create a directory inside this data folder to host the numpy arrays created after parsing the files)

Thank you soo much, you saved my life :'( @thomwolf
