### ISSUE TITLE
(base) C:\Users\sk136\neuralcoref>python -m neuralcoref.train.learn --train ./data/train/ --eval ./data/dev/ facing problem while executing.. this command

### ISSUE THREAD

**Issue by sandeep16064** [huggingface/neuralcoref#346]
.
.
.
🌋 Construct test file
Writing in C:\Users\sk136\neuralcoref\neuralcoref\train\test_mentions.txt
🌋 Computing score
Error during the scoring
Command '['perl', 'C:\\Users\\sk136\\neuralcoref\\neuralcoref\\train\\scorer_wrapper.pl', 'muc', './data/dev//key.txt', 'C:\\Users\\sk136\\neuralcoref\\neuralcoref\\train\\test_mentions.txt']' returned non-zero exit status 2.
Can't locate CorScorer.pm in @INC (you may need to install the CorScorer module) (@INC contains: scorer/lib /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at C:\Users\sk136\neuralcoref\neuralcoref\train\scorer_wrapper.pl line 16.
BEGIN failed--compilation aborted at C:\Users\sk136\neuralcoref\neuralcoref\train\scorer_wrapper.pl line 16.

Traceback (most recent call last):
  File "C:\Users\sk136\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sk136\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sk136\neuralcoref\neuralcoref\train\learn.py", line 565, in <module>
    run_model(args)
  File "C:\Users\sk136\neuralcoref\neuralcoref\train\learn.py", line 175, in run_model
    eval_evaluator.test_model()
  File "C:\Users\sk136\neuralcoref\neuralcoref\train\evaluator.py", line 180, in test_model
    self.get_score(file_path=ALL_MENTIONS_PATH)
  File "C:\Users\sk136\neuralcoref\neuralcoref\train\evaluator.py", line 283, in get_score
    scorer_out = subprocess.check_output(
  File "C:\Users\sk136\anaconda3\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\sk136\anaconda3\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['perl', 'C:\\Users\\sk136\\neuralcoref\\neuralcoref\\train\\scorer_wrapper.pl', 'muc', './data/dev//key.txt', 'C:\\Users\\sk136\\neuralcoref\\neuralcoref\\train\\test_mentions.txt']' returned non-zero exit status 2.

perl related issue

**Comment by AngledLuffa** [comment]
Without knowing much about your setup, if you downloaded the scorer script from the conll bakeoffs, there's a good chance your downloaded package has a `lib` directory which has `CorScorer.pm` in it
