### ISSUE TITLE
installation failed with

### ISSUE THREAD

**Issue by arademaker** [huggingface/neuralcoref#361]
```
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/usr/local/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -I/private/var/folders/b_/7nbv248s2nq019mcx58xrrb80000gn/T/pip-install-4w4tbrnm/neuralcoref_ec8382bdcf32461da12bc431aa5c3c71/include -I/Users/ar/work/cpdoc/dhbb-nlp/venv/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c neuralcoref/neuralcoref.cpp -o build/temp.macosx-14-x86_64-cpython-311/neuralcoref/neuralcoref.o -O2 -Wno-strict-prototypes -Wno-unused-function
      neuralcoref/neuralcoref.cpp:196:12: fatal error: 'longintrepr.h' file not found
        #include "longintrepr.h"
                 ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

```

any idea? I was following the README

**Comment by ZheXu-Joseph** [comment]
you can try upgrading Cpython/ downgrading python/ installing build-essential

**Comment by tommybbq** [comment]
Did you overcome this error @arademaker ?

**Comment by mboogerd** [comment]
I'm on a MacBook Pro from 2019 (2,3 GHz 8-Core Intel Core i9), macOS Sonoma 14.4.1 (23E224) and experienced the issue @arademaker mentioned, and tried a variety of python versions:
- `3.11.2`: Failed with the same error as above
- `3.10.10`: Failed due to instances of `neuralcoref.cpp:49376:72: error: no member named 'tp_print' in '_typeobject'`
- `3.9.16`: Failed due to instances of  `neuralcoref.cpp:49376:72: error: no member named 'tp_print' in '_typeobject'`
- `3.8.16`: Succeeded

Just to share my experience and a possible way forward for others, i.e. using python 3.8(.16)

**Edit**: Celebrations were premature. My `3.8.16` installation cannot run the [example](https://spacy.io/universe/project/neuralcoref) due to #310 

**Edit 2**: After some digging, this repository [seems to have been abandoned](https://github.com/huggingface/neuralcoref/issues/295#issuecomment-859005189) in favour of an integration within spaCy directly, although it still lives in [spaCy-experimental](https://github.com/explosion/spaCy/pull/7264#issuecomment-1270146915)

**Comment by arademaker** [comment]
No solution yet, right?

```
     clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/opt/homebrew/opt/llvm/include -I/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -I/private/var/folders/__/49tv_g9s6278ljp2ld68b0l40000gn/T/pip-install-uu3c1u75/neuralcoref_f0fc437021f14c30bd3ee7814510fd2a/include -I/Users/ar/r/mrs-logic/venv/include -I/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c neuralcoref/neuralcoref.cpp -o build/temp.macosx-14.0-arm64-cpython-312/neuralcoref/neuralcoref.o -O2 -Wno-strict-prototypes -Wno-unused-function
      neuralcoref/neuralcoref.cpp:196:12: fatal error: 'longintrepr.h' file not found
        196 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/opt/homebrew/opt/llvm/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for neuralcoref
Failed to build neuralcoref
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (neuralcoref)
(venv) ar@tranco mrs-logic %
```

**Comment by rydeveraumn** [comment]
I am getting this error in a `linux` environment:

```
pip install neuralcoref
Collecting neuralcoref
  Downloading neuralcoref-4.0.tar.gz (368 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-39l4l_fh/neuralcoref_113087f6716f4683bba9e5909f56a7d9/setup.py", line 46, in <module>
          from distutils import ccompiler, msvccompiler
      ImportError: cannot import name 'msvccompiler' from 'distutils' (/users/5/dever120/.conda/envs/selective-prediction/lib/python3.12/site-packages/setuptools/_distutils/__init__.py). Did you mean: 'ccompiler'?
```
