### ISSUE TITLE
ValueError: [E090] Extension 'has_coref' already exists on Doc. To overwrite the existing extension, set `force=True` on `Doc.set_extension`.

### ISSUE THREAD

**Issue by kyoungrok0517** [huggingface/neuralcoref#52]
Hi, I see the following error when I do `nlp = spacy.load('en_coref_sm')` in dask partition. Any compatibility issue with dask?

```
Traceback (most recent call last):
  File "180606_coreference_dev.py", line 52, in <module>
    d.compute()
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/dask/base.py", line 400, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/dask/threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/dask/compatibility.py", line 68, in reraise
    raise exc
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/dask/dataframe/core.py", line 3549, in apply_and_enforce
    df = func(*args, **kwargs)
  File "180606_coreference_dev.py", line 30, in process_partition
    nlp = spacy.load('en_coref_sm')
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/spacy/__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/spacy/util.py", line 114, in load_model
    return load_model_from_package(name, **overrides)
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/spacy/util.py", line 135, in load_model_from_package
    return cls.load(**overrides)
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/en_coref_sm/__init__.py", line 15, in load
    coref = NeuralCoref(nlp.vocab)
  File "neuralcoref.pyx", line 495, in neuralcoref.neuralcoref.NeuralCoref.__init__
  File "doc.pyx", line 100, in spacy.tokens.doc.Doc.set_extension
ValueError: [E090] Extension 'has_coref' already exists on Doc. To overwrite the existing extension, set `force=True` on `Doc.set_extension`.

```

**Comment by thomwolf** [comment]
I don't know how dask is using neuralcoref. Did you add this integration? If not I guess the best would be to ask the dask team, maybe?

**Comment by thomwolf** [comment]
I think it does.

Normally this error arise when you initiate several time the NeuralCoref pipeline object as the extension are added globally and not just on a particular instance (https://spacy.io/usage/processing-pipelines#custom-components-extensions).

This error is here to prevent namespace collision on the extension attributes from several pipelines modules that would add attributes with the same names. So I don't think it would be wise to hide it in a try...catch... statement.

Can you try creating your `nlp` object outside of the `process_partition` function so that it's `__init__` is only called once?

**Comment by kyoungrok0517** [comment]
Seems that works. Thanks!
