### ISSUE TITLE
Token level coref_clusters access raise exceptions sometimes

### ISSUE THREAD

**Issue by theSage21** [huggingface/neuralcoref#58]
```python
import spacy

nlp = spacy.load('en_coref_sm')

x = '''The English name "Normans" comes from the French words Normans/Normanz, plural of Normant, modern French normand, which is itself borrowed from Old Low Franconian Nortmann "Northman" or directly from Old Norse Norðmaðr, Latinized variously as Nortmannus, Normannus, or Nordmannus (recorded in Medieval Latin, 9th century) to mean "Norseman, Viking". What is the original meaning of the word Norman?'''
doc = nlp(x)
doc[0]._.coref_clusters
```

Raises an error.

```
Traceback (most recent call last):
  File "bug.py", line 7, in <module>
    doc[0]._.coref_clusters
  File "/home/arjoonn/.local/share/virtualenvs/squad2.0-PnAXOzWu/lib/python3.6/site-packages/spacy/tokens/underscore.py", line 31, in __getattr__
    return getter(self._obj)
  File "neuralcoref.pyx", line 800, in en_coref_sm.neuralcoref.neuralcoref.NeuralCoref.token_clusters
TypeError: 'NoneType' object is not iterable
```

This only happens sometimes (for example with the text given above).

**Comment by theSage21** [comment]
I'm sorry. I should have included that.
Ubuntu 18.04, Python 3.6.2

**Comment by theSage21** [comment]
Ok. So this happens whenever there's no actual coref in the text.

```python
import spacy
nlp = spacy.load('en_coref_sm')
doc = nlp('john was walking down the road.')
doc[0]._.coref_clusters
```

Could be because of https://github.com/huggingface/neuralcoref/blob/master/neuralcoref/neuralcoref.pyx#L802

I don't know enough about packaging and cython to verify if this is indeed the problem. My changes are not picked up by cython (?). If it is the issue, I'll be happy to put in a pull request.

**Comment by thomwolf** [comment]
Hi @theSage21, I finally found time to work on NeuralCoref.
This should be fixed in the new release (4.0).

**Comment by rudraksh97** [comment]
I am using en_coref_md. I am getting this error. How to resolve this?

**Comment by floraliu1011** [comment]
I am using en and I also got this problem
