### ISSUE TITLE
Error while running server.py in examples

### ISSUE THREAD

**Issue by sarthakchakravarty** [huggingface/neuralcoref#62]
I am trying to run the server.py file in the examples and I am getting the following error.

```python
Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/formcept/neuralcoref/neuralconf/lib/python3.5/site-packages/falcon/api.py", line 244, in __call__
    responder(req, resp, **params)
  File "server.py", line 39, in on_get
    } for span in doc._.coref_mentions]
  File "/home/formcept/neuralcoref/neuralconf/lib/python3.5/site-packages/spacy/tokens/underscore.py", line 28, in __getattr__
    raise AttributeError(Errors.E046.format(name=name))
AttributeError: [E046] Can't retrieve unregistered extension attribute 'coref_mentions'. Did you forget to call the `set_extension` method?
```

I am using Ubuntu 16.04 and python3

**Comment by sarthakchakravarty** [comment]
I did a work around this error for my use case with the following piece of code:
```python3
mentions = [{'start': span.start_char,
             'end': span.end_char,
             'text': span.text,
             'resolved': cluster.main.text
            } for cluster in clusters for span in cluster]
```
You can check if this solves your problem too.

**Comment by haijun-dgp** [comment]
Yeah I found out that too. Apparently they only support certain types of attributes, as they mentioned in the readme of the repo.

**Comment by thomwolf** [comment]
This is fixed now.
