### ISSUE TITLE
AttributeError: coref_clusters

### ISSUE THREAD

**Issue by linkwithkk** [huggingface/neuralcoref#64]
Win 10
spacy==2.0.8
neuralcoref==3.0
en-coref-lg==3.0.0

I get the following error when I run the demo code.

**************************************************************
doc = nlp(u'My sister has a dog. She loves him.')
Traceback (most recent call last):

  File "<ipython-input-11-2b2717409135>", line 1, in <module>
    doc = nlp(u'My sister has a dog. She loves him.')

  File "D:\anaconda3\lib\site-packages\spacy\language.py", line 341, in __call__
    doc = proc(doc)

  File "neuralcoref.pyx", line 566, in en_coref_lg.neuralcoref.neuralcoref.NeuralCoref.__call__

  File "neuralcoref.pyx", line 785, in en_coref_lg.neuralcoref.neuralcoref.NeuralCoref.set_annotations

  File "D:\anaconda3\lib\site-packages\spacy\tokens\underscore.py", line 45, in set
    return self.__setattr__(name, value)

  File "D:\anaconda3\lib\site-packages\spacy\tokens\underscore.py", line 37, in __setattr__
    raise AttributeError(name)

AttributeError: coref_clusters

**Comment by thomwolf** [comment]
Hi @linkwithkk,
Can you try updating to the latest version of spacy (I recommend doing that in a conda environment)?
You can do that, for example, by installing NeuralCoref in a clean environment with:
```bash
pip install --upgrade --force-reinstall --no-cache-dir MODEL_URL
```

**Comment by Rishabh-Choudhry** [comment]
Received the same error in macos, any solution @thomwolf ?
Tried :  **pip install --upgrade --force-reinstall --no-cache-dir MODEL_URL** 
but did not work

**Comment by pandiaraj** [comment]
@thomwolf Thanks, upgrading to Spacy2.0.11 works on Windows 10

**Comment by cgallay** [comment]
@thomwolf Thanks, upgrading to spacy-2.0.12 worked form me as well on Linux

**Comment by theSage21** [comment]
@linkwithkk does this work for you?

**Comment by linkwithkk** [comment]
Hi guys. I ended up taking a different approach for my problem.
However i tried it now with 2.0.11 and it works.

**Comment by thomwolf** [comment]
This is fixed now.
