### ISSUE TITLE
KeyError at vectors.pyx

### ISSUE THREAD

**Issue by kyoungrok0517** [huggingface/neuralcoref#98]
Hello, I encounter the following error. I'm using the latest `en_coref_lg` model, spacy 2.0.11.

```python
Traceback (most recent call last):
  File "coref_and_split_sentences.py", line 40, in <module>
    b.compute()
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/dask/base.py", line 400, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/dask/multiprocessing.py", line 177, in get
    raise_exception=reraise, **kwargs)
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/dask/compatibility.py", line 67, in reraise
    raise exc.with_traceback(tb)
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/dask/compatibility.py", line 51, in apply
    return func(*args)
  File "coref_and_split_sentences.py", line 23, in process
    doc = nlp(paragraph)
  File "/home/kyoungrok/anaconda3/envs/coref/lib/python3.6/site-packages/spacy/language.py", line 352, in __call__
    doc = proc(doc)
  File "neuralcoref.pyx", line 564, in en_coref_lg.neuralcoref.neuralcoref.NeuralCoref.__call__
  File "neuralcoref.pyx", line 690, in en_coref_lg.neuralcoref.neuralcoref.NeuralCoref.predict
  File "neuralcoref.pyx", line 845, in en_coref_lg.neuralcoref.neuralcoref.NeuralCoref.get_mention_embeddings
  File "neuralcoref.pyx", line 835, in en_coref_lg.neuralcoref.neuralcoref.NeuralCoref.get_average_embedding
  File "neuralcoref.pyx", line 821, in en_coref_lg.neuralcoref.neuralcoref.NeuralCoref.get_word_embedding
  File "neuralcoref.pyx", line 813, in en_coref_lg.neuralcoref.neuralcoref.NeuralCoref.get_static
  File "vectors.pyx", line 116, in spacy.vectors.Vectors.__getitem__
KeyError: 77186543510594498
```

**Comment by thomwolf** [comment]
Fixed in the new release (4.0).
